[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
	mikalhart/TinyGPSPlus@^1.0.3
	bblanchon/ArduinoJson@^7.0.0
	knolleary/PubSubClient@^2.8

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	mikalhart/TinyGPSPlus@^1.0.3
	bblanchon/ArduinoJson@^7.0.0
	knolleary/PubSubClient@^2.8

